#!/usr/bin/env node
// Regenerate chikin-browser.json — the seccomp profile the gateway attaches to
// every fleet browser so Chrome's user-namespace sandbox can run under
// CapDrop:["ALL"] + no-new-privileges (see gateway/src/provisioner.ts and the
// H1 renderer-escape hardening).
//
// The profile is DERIVED, never hand-maintained: it is moby's own default
// seccomp profile (the exact set of default-deny rules Docker ships) plus ONE
// prepended allow group for the five syscalls Chrome's namespace sandbox needs.
// Deriving from upstream means every other default-deny rule (mount, bpf,
// ptrace, kexec, keyring, perf_event_open, …) stays intact and tracks Docker as
// it evolves — refresh by bumping MOBY_REF and re-running this script.
//
// Why these five, and why unconditional:
//   Docker's default gates clone/clone3/unshare/setns behind CAP_SYS_ADMIN and
//   chroot behind CAP_SYS_CHROOT (and its unconditional `clone` rule masks off
//   the CLONE_NEW* namespace-creation flags). chikin drops ALL capabilities, so
//   Chrome's zygote can't create its user/PID/NET namespaces or chroot the
//   renderer → the zygote aborts (exit 133). Allowing exactly these five
//   unconditionally lets the namespace sandbox build itself WITHOUT handing the
//   container any capability — the far more dangerous cap-gated syscalls sharing
//   moby's group (mount, bpf, perf_event_open, …) remain default-denied.
//
// Usage:  node gateway/seccomp/generate.mjs   (writes chikin-browser.json)
//         MOBY_REF=v28.3.0 node gateway/seccomp/generate.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Pin the upstream default profile to a released moby tag for reproducibility.
// Bump this to refresh against a newer Docker default, then re-run.
const MOBY_REF = process.env.MOBY_REF || "v28.3.0";
const SRC = `https://raw.githubusercontent.com/moby/moby/${MOBY_REF}/profiles/seccomp/default.json`;

// The single widening: allow the namespace/chroot syscalls unconditionally.
// Prepended so it is matched BEFORE moby's cap-gated group for the same names.
const ALLOW_GROUP = {
  names: ["clone", "clone3", "unshare", "setns", "chroot"],
  action: "SCMP_ACT_ALLOW",
  comment:
    "chikin: allow Chrome's user-namespace sandbox to build its namespaces + chroot the " +
    "renderer under CapDrop:[ALL] + no-new-privileges. Prepended to moby's default so it " +
    "wins over the CAP_SYS_ADMIN/CAP_SYS_CHROOT-gated rules for these names.",
};

const NAMES = new Set(ALLOW_GROUP.names);

async function main() {
  const res = await fetch(SRC);
  if (!res.ok) {
    throw new Error(`fetch ${SRC} failed: ${res.status} ${res.statusText}`);
  }
  const profile = await res.json();

  if (profile.defaultAction !== "SCMP_ACT_ERRNO" || !Array.isArray(profile.syscalls)) {
    throw new Error("unexpected moby default profile shape — refusing to derive from it");
  }

  // Sanity-check that upstream still gates these behind caps (i.e. our widening
  // is still meaningful). If moby ever allows them by default, flag it loudly.
  const stillGated = profile.syscalls.some(
    (g) =>
      g.action === "SCMP_ACT_ALLOW" &&
      g.includes?.caps?.length &&
      g.names?.some((n) => NAMES.has(n)),
  );
  if (!stillGated) {
    console.warn(
      "warning: moby default no longer cap-gates any of " +
        [...NAMES].join(",") +
        " — the widening may be redundant; review before shipping.",
    );
  }

  const out = {
    __chikin: {
      note:
        "GENERATED by gateway/seccomp/generate.mjs — do not edit by hand. " +
        "moby default seccomp + one prepended allow group for Chrome's userns sandbox.",
      mobyRef: MOBY_REF,
      source: SRC,
      addedAllowGroup: ALLOW_GROUP.names,
    },
    ...profile,
    syscalls: [ALLOW_GROUP, ...profile.syscalls],
  };

  const dest = fileURLToPath(new URL("./chikin-browser.json", import.meta.url));
  writeFileSync(dest, JSON.stringify(out, null, 2) + "\n");
  console.log(`wrote ${dest} (moby ${MOBY_REF}, +${ALLOW_GROUP.names.length} allowed syscalls)`);
}

main().catch((e) => {
  console.error(e.stack || e.message);
  process.exit(1);
});
